"""changed model template

Revision ID: 030925136aaf
Revises: c2f3828b8958
Create Date: 2023-04-02 12:58:44.571967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030925136aaf'
down_revision = 'c2f3828b8958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bucket', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('region')
        batch_op.drop_column('bucket')

    # ### end Alembic commands ###
