"""change Prompt model to new route

Revision ID: 18ea328a9286
Revises: 9b9950f3d0bc
Create Date: 2023-11-18 21:10:57.628888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ea328a9286'
down_revision = '9b9950f3d0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_type', sa.String(), nullable=False))
        batch_op.drop_column('provider')
        batch_op.drop_column('request')
        batch_op.drop_column('method')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('premium')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('request', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('prompt_type')

    # ### end Alembic commands ###
