"""stripe date infos

Revision ID: 22cd0d2af6ef
Revises: 440c44bf3a37
Create Date: 2024-03-08 11:59:10.388596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cd0d2af6ef'
down_revision = '440c44bf3a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
