"""Favoriten model

Revision ID: 530ca4c3c5d0
Revises: d44e2ef43de6
Create Date: 2023-03-11 13:47:26.958897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530ca4c3c5d0'
down_revision = 'd44e2ef43de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_method', sa.String(), nullable=False),
    sa.Column('favorite_type', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('favorite_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
