"""empty message

Revision ID: 7756fdf13cb7
Revises: 58a8fbd20675
Create Date: 2024-01-03 12:50:24.936511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7756fdf13cb7'
down_revision = '58a8fbd20675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_column('sub_prompt_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_prompt_type', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
