"""added email from oauth provider

Revision ID: 98d82f83e1df
Revises: b99dc0018fb5
Create Date: 2023-11-14 18:04:10.789908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d82f83e1df'
down_revision = 'b99dc0018fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_user_email', sa.String(length=400), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_dance_oauth', schema=None) as batch_op:
        batch_op.drop_column('provider_user_email')

    # ### end Alembic commands ###
