"""changed templates model

Revision ID: c308800b44ad
Revises: dcc83a863fe3
Create Date: 2023-04-04 14:12:05.310360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c308800b44ad'
down_revision = 'dcc83a863fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('s3_bucket_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_bucket_link', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
