"""changed prompt model

Revision ID: eed5bed15fc5
Revises: 18ea328a9286
Create Date: 2023-11-19 17:42:13.995415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed5bed15fc5'
down_revision = '18ea328a9286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(), nullable=True))
        batch_op.alter_column('favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('command')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('premium')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('result')

    # ### end Alembic commands ###
