"""number of prompts and tokens added to user model

Revision ID: f9896190aa5d
Revises: e6d9dedaf324
Create Date: 2023-03-15 14:54:38.187682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9896190aa5d'
down_revision = 'e6d9dedaf324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_prompts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('num_tokens', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('num_tokens')
        batch_op.drop_column('num_prompts')

    # ### end Alembic commands ###
